# Generated by Django 6.0 on 2025-12-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examrecord',
            unique_together=set(),
        ),
    ]
